#!/bin/bash
# vim: set ft=sh


set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload="$(ping 10.33.56.89 -c 2)"

cat > "${payload}" <&0
